# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/benjamin/cs_345/lab1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/benjamin/cs_345/lab1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benjamin/cs_345/lab1/CMakeFiles /home/benjamin/cs_345/lab1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benjamin/cs_345/lab1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_shell

# Build rule for target.
my_shell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_shell
.PHONY : my_shell

# fast build rule for target.
my_shell/fast:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/build
.PHONY : my_shell/fast

os345.o: os345.c.o
.PHONY : os345.o

# target to build an object file
os345.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345.c.o
.PHONY : os345.c.o

os345.i: os345.c.i
.PHONY : os345.i

# target to preprocess a source file
os345.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345.c.i
.PHONY : os345.c.i

os345.s: os345.c.s
.PHONY : os345.s

# target to generate assembly for a file
os345.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345.c.s
.PHONY : os345.c.s

os345fat.o: os345fat.c.o
.PHONY : os345fat.o

# target to build an object file
os345fat.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345fat.c.o
.PHONY : os345fat.c.o

os345fat.i: os345fat.c.i
.PHONY : os345fat.i

# target to preprocess a source file
os345fat.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345fat.c.i
.PHONY : os345fat.c.i

os345fat.s: os345fat.c.s
.PHONY : os345fat.s

# target to generate assembly for a file
os345fat.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345fat.c.s
.PHONY : os345fat.c.s

os345interrupts.o: os345interrupts.c.o
.PHONY : os345interrupts.o

# target to build an object file
os345interrupts.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345interrupts.c.o
.PHONY : os345interrupts.c.o

os345interrupts.i: os345interrupts.c.i
.PHONY : os345interrupts.i

# target to preprocess a source file
os345interrupts.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345interrupts.c.i
.PHONY : os345interrupts.c.i

os345interrupts.s: os345interrupts.c.s
.PHONY : os345interrupts.s

# target to generate assembly for a file
os345interrupts.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345interrupts.c.s
.PHONY : os345interrupts.c.s

os345lc3.o: os345lc3.c.o
.PHONY : os345lc3.o

# target to build an object file
os345lc3.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345lc3.c.o
.PHONY : os345lc3.c.o

os345lc3.i: os345lc3.c.i
.PHONY : os345lc3.i

# target to preprocess a source file
os345lc3.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345lc3.c.i
.PHONY : os345lc3.c.i

os345lc3.s: os345lc3.c.s
.PHONY : os345lc3.s

# target to generate assembly for a file
os345lc3.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345lc3.c.s
.PHONY : os345lc3.c.s

os345mmu.o: os345mmu.c.o
.PHONY : os345mmu.o

# target to build an object file
os345mmu.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345mmu.c.o
.PHONY : os345mmu.c.o

os345mmu.i: os345mmu.c.i
.PHONY : os345mmu.i

# target to preprocess a source file
os345mmu.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345mmu.c.i
.PHONY : os345mmu.c.i

os345mmu.s: os345mmu.c.s
.PHONY : os345mmu.s

# target to generate assembly for a file
os345mmu.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345mmu.c.s
.PHONY : os345mmu.c.s

os345p1.o: os345p1.c.o
.PHONY : os345p1.o

# target to build an object file
os345p1.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p1.c.o
.PHONY : os345p1.c.o

os345p1.i: os345p1.c.i
.PHONY : os345p1.i

# target to preprocess a source file
os345p1.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p1.c.i
.PHONY : os345p1.c.i

os345p1.s: os345p1.c.s
.PHONY : os345p1.s

# target to generate assembly for a file
os345p1.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p1.c.s
.PHONY : os345p1.c.s

os345p2.o: os345p2.c.o
.PHONY : os345p2.o

# target to build an object file
os345p2.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p2.c.o
.PHONY : os345p2.c.o

os345p2.i: os345p2.c.i
.PHONY : os345p2.i

# target to preprocess a source file
os345p2.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p2.c.i
.PHONY : os345p2.c.i

os345p2.s: os345p2.c.s
.PHONY : os345p2.s

# target to generate assembly for a file
os345p2.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p2.c.s
.PHONY : os345p2.c.s

os345p3.o: os345p3.c.o
.PHONY : os345p3.o

# target to build an object file
os345p3.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p3.c.o
.PHONY : os345p3.c.o

os345p3.i: os345p3.c.i
.PHONY : os345p3.i

# target to preprocess a source file
os345p3.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p3.c.i
.PHONY : os345p3.c.i

os345p3.s: os345p3.c.s
.PHONY : os345p3.s

# target to generate assembly for a file
os345p3.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p3.c.s
.PHONY : os345p3.c.s

os345p4.o: os345p4.c.o
.PHONY : os345p4.o

# target to build an object file
os345p4.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p4.c.o
.PHONY : os345p4.c.o

os345p4.i: os345p4.c.i
.PHONY : os345p4.i

# target to preprocess a source file
os345p4.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p4.c.i
.PHONY : os345p4.c.i

os345p4.s: os345p4.c.s
.PHONY : os345p4.s

# target to generate assembly for a file
os345p4.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p4.c.s
.PHONY : os345p4.c.s

os345p5.o: os345p5.c.o
.PHONY : os345p5.o

# target to build an object file
os345p5.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p5.c.o
.PHONY : os345p5.c.o

os345p5.i: os345p5.c.i
.PHONY : os345p5.i

# target to preprocess a source file
os345p5.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p5.c.i
.PHONY : os345p5.c.i

os345p5.s: os345p5.c.s
.PHONY : os345p5.s

# target to generate assembly for a file
os345p5.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p5.c.s
.PHONY : os345p5.c.s

os345p6.o: os345p6.c.o
.PHONY : os345p6.o

# target to build an object file
os345p6.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p6.c.o
.PHONY : os345p6.c.o

os345p6.i: os345p6.c.i
.PHONY : os345p6.i

# target to preprocess a source file
os345p6.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p6.c.i
.PHONY : os345p6.c.i

os345p6.s: os345p6.c.s
.PHONY : os345p6.s

# target to generate assembly for a file
os345p6.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345p6.c.s
.PHONY : os345p6.c.s

os345park.o: os345park.c.o
.PHONY : os345park.o

# target to build an object file
os345park.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345park.c.o
.PHONY : os345park.c.o

os345park.i: os345park.c.i
.PHONY : os345park.i

# target to preprocess a source file
os345park.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345park.c.i
.PHONY : os345park.c.i

os345park.s: os345park.c.s
.PHONY : os345park.s

# target to generate assembly for a file
os345park.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345park.c.s
.PHONY : os345park.c.s

os345semaphores.o: os345semaphores.c.o
.PHONY : os345semaphores.o

# target to build an object file
os345semaphores.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345semaphores.c.o
.PHONY : os345semaphores.c.o

os345semaphores.i: os345semaphores.c.i
.PHONY : os345semaphores.i

# target to preprocess a source file
os345semaphores.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345semaphores.c.i
.PHONY : os345semaphores.c.i

os345semaphores.s: os345semaphores.c.s
.PHONY : os345semaphores.s

# target to generate assembly for a file
os345semaphores.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345semaphores.c.s
.PHONY : os345semaphores.c.s

os345signals.o: os345signals.c.o
.PHONY : os345signals.o

# target to build an object file
os345signals.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345signals.c.o
.PHONY : os345signals.c.o

os345signals.i: os345signals.c.i
.PHONY : os345signals.i

# target to preprocess a source file
os345signals.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345signals.c.i
.PHONY : os345signals.c.i

os345signals.s: os345signals.c.s
.PHONY : os345signals.s

# target to generate assembly for a file
os345signals.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345signals.c.s
.PHONY : os345signals.c.s

os345tasks.o: os345tasks.c.o
.PHONY : os345tasks.o

# target to build an object file
os345tasks.c.o:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345tasks.c.o
.PHONY : os345tasks.c.o

os345tasks.i: os345tasks.c.i
.PHONY : os345tasks.i

# target to preprocess a source file
os345tasks.c.i:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345tasks.c.i
.PHONY : os345tasks.c.i

os345tasks.s: os345tasks.c.s
.PHONY : os345tasks.s

# target to generate assembly for a file
os345tasks.c.s:
	$(MAKE) -f CMakeFiles/my_shell.dir/build.make CMakeFiles/my_shell.dir/os345tasks.c.s
.PHONY : os345tasks.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... my_shell"
	@echo "... rebuild_cache"
	@echo "... os345.o"
	@echo "... os345.i"
	@echo "... os345.s"
	@echo "... os345fat.o"
	@echo "... os345fat.i"
	@echo "... os345fat.s"
	@echo "... os345interrupts.o"
	@echo "... os345interrupts.i"
	@echo "... os345interrupts.s"
	@echo "... os345lc3.o"
	@echo "... os345lc3.i"
	@echo "... os345lc3.s"
	@echo "... os345mmu.o"
	@echo "... os345mmu.i"
	@echo "... os345mmu.s"
	@echo "... os345p1.o"
	@echo "... os345p1.i"
	@echo "... os345p1.s"
	@echo "... os345p2.o"
	@echo "... os345p2.i"
	@echo "... os345p2.s"
	@echo "... os345p3.o"
	@echo "... os345p3.i"
	@echo "... os345p3.s"
	@echo "... os345p4.o"
	@echo "... os345p4.i"
	@echo "... os345p4.s"
	@echo "... os345p5.o"
	@echo "... os345p5.i"
	@echo "... os345p5.s"
	@echo "... os345p6.o"
	@echo "... os345p6.i"
	@echo "... os345p6.s"
	@echo "... os345park.o"
	@echo "... os345park.i"
	@echo "... os345park.s"
	@echo "... os345semaphores.o"
	@echo "... os345semaphores.i"
	@echo "... os345semaphores.s"
	@echo "... os345signals.o"
	@echo "... os345signals.i"
	@echo "... os345signals.s"
	@echo "... os345tasks.o"
	@echo "... os345tasks.i"
	@echo "... os345tasks.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

